config/routes.rb
WastedUs::Application.routes.draw do
  resources :meetings, except: [:destroy, :index]

  post 'meetings/:id/twilio/', to: 'meetings#twilio'

  root 'meetings#new'

  get '/email', :to => "email#email", :as => :post

  # get '/meeting(/:id)', :to => "meetings#show", :as => :meeting, :via => :get
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def email
    # Your domain
    domain = "wasted.us"

    # From Email Address
    from_address = "wasted@wasted.us"

    # To Email Address
    to_address = params[:email]

    # Subject
    subject = "Thanks for using Wasted!"

    # Text Body
    text = "You wasted a lot of time.\n\n" + "Your meeting cost $#{params[:cost]}.\n\n" +  params[:meeting_notes] + "\n\nLove,\nYour friends at Wasted"

    # HTML Body
    html = "<table style=\"border: solid 1px #000; background-color: #666; font-family: verdana, tahoma, sans-serif; color: #fff;\"> <tr> <td> <h2>Hello,</h2> <p>This is a test message from SendGrid.    We have sent this to you because you requested a test message be sent from your account.</p> <a href=\"http://www.google.com\" target=\"_blank\">This is a link to google.com</a> <p> <a href=\"http://www.apple.com\" target=\"_blank\">This is a link to apple.com</a> <p> <a href=\"http://www.sendgrid.com\" target=\"_blank\">This is a link to sendgrid.com</a> </p> <p>Thank you for reading this test message.</p> Love,<br/> Your friends at SendGrid</p> <p> <img src=\"http://cdn1.sendgrid.com/images/sendgrid-logo.png\" alt=\"SendGrid!\" /> </td> </tr> </table>"

    begin

      require "rubygems"
      require "mail"
      require "json"

      sg_username = "ksweet"
      sg_password = Rails.application.secrets.sg_password

      Mail.defaults do
        delivery_method :smtp, { :address   => "smtp.sendgrid.net",
                                 :port      => 587,
                                 :domain    => domain,
                                 :user_name => sg_username,
                                 :password  => sg_password,
                                 :authentication => "plain",
                                 :enable_starttls_auto => true }
      end
      mail = Mail.deliver do
        to to_address
        from from_address
        subject subject
        text_part do
          body text
        end
        # html_part do
        #   content_type "text/html; charset=UTF-8"
        #   body html
        # end
      end

      puts "Email sent successfully."

      redirect_to '/meetings/' + params[:id]
    rescue Exception => e
      puts e.message
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.checked_out_participant_count = 0
    @meeting.participant_count ||= 0
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meeting }
      else
        format.html { render action: 'new' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.json { head :no_content }
      else
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end

  def twilio
    meeting = Meeting.find(params[:id])
    account_sid = Rails.application.secrets.twilio_account_sid
    auth_token = Rails.application.secrets.twilio_auth_token
    twilio_phone_number = Rails.application.secrets.twilio_phone_number

    client = Twilio::REST::Client.new account_sid, auth_token

    client.account.messages.create({
                                       :from => twilio_phone_number,
                                       :to => params[:phone_number_to_text],
                                       :body => 'Time is wasting. Enter the meeting here: ' +
                                           meetings_url + '/' + meeting.id.to_s
                                   })
    redirect_to '/meetings/' + meeting.id.to_s
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:start_time, :end_time, :name, :participant_count, :salary, :cost, :location, :agenda, :actions, :checked_out_participant_count, :phone_number_to_text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WastedUs
    %link{:rel => 'Shortcut Icon', :href => "#{image_path('favicon.ico')}"}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1'}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag "http://yui.yahooapis.com/pure/0.5.0/forms-min.css", :media => "all"
    = stylesheet_link_tag params[:controller], :media => "all"
    = yield :css
    %link{href: "http://fonts.googleapis.com/css?family=Oxygen", rel: "stylesheet", type: "text/css"}/
    = csrf_meta_tags
  %body
    = yield
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield :javascript

app/views/meetings/_form.html.haml
= form_for @meeting do |f|
  - if @meeting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meeting.errors.count, "error")} prohibited this meeting from being saved:"
      %ul
        - @meeting.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :end_time
    = f.datetime_select :end_time
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :participant_count
    = f.number_field :participant_count
  .field
    = f.label :salary
    = f.text_field :salary
  .field
    = f.label :cost
    = f.text_field :cost
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :agenda
    = f.text_field :agenda
  .field
    = f.label :actions
    = f.text_field :actions
  .actions
    = f.submit 'Save'

app/views/meetings/edit.html.haml
%h1 Editing meeting

= render 'form'

= link_to 'Show', @meeting
\|
= link_to 'Back', meetings_path

app/views/meetings/index.html.haml
%h1 Listing meetings

%table
  %tr
    %th Start time
    %th End time
    %th Participant count
    %th Cost
    %th Location
    %th Agenda
    %th Actions
    %th
    %th
    %th

  - @meetings.each do |meeting|
    %tr
      %td= meeting.start_time
      %td= meeting.end_time
      %td= meeting.participant_count
      %td= meeting.cost
      %td= meeting.location
      %td= meeting.agenda
      %td= meeting.actions
      %td= link_to 'Show', meeting
      %td= link_to 'Edit', edit_meeting_path(meeting)
      %td= link_to 'Destroy', meeting, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Meeting', new_meeting_path

app/views/meetings/new.html.haml
= content_for :javascript do
  = javascript_include_tag "meetings-new"
= content_for :css do
  = stylesheet_link_tag "meetings-new"
#welcome-page
  %h1 wasted
  %p#tagline find out how much money you're wasting
  #main-form-wrapper
    -#%form{:for => @meeting, :id => "main-form", :class => "pure-form"}
    = form_for @meeting, url: {action: 'create'}, :class => "pure-form" do |f|
      = f.text_field :participant_count, :placeholder => "How many people are in the meeting?"
      = f.text_field :salary, :value => "90000", :data => {:slider => "true", :slider_range => "10000,200000", :slider_step => "5000"}
      %span.output
        Average Salary: $90,000
      %input{:type => "submit", :value => "Start Meeting", :class => "btn btn-success", :id => "main-form-submit"}

app/views/meetings/show.html.haml
= content_for :javascript do
  = javascript_include_tag "meetings-show"
  = javascript_include_tag "meetings-done"
= content_for :css do
  = stylesheet_link_tag "meetings-show"
#counter-page{:data => {:id => @meeting.id,
                        :participant_count => @meeting.participant_count,
                        :checked_out_participant_count => @meeting.checked_out_participant_count,
                        :salary => @meeting.salary,
                        :cost => @meeting.cost,
                        :finished => @meeting.end_time}}
  #url-wrapper.hideable
    %div
      %button{:class => "btn btn-default", :id => "share-meeting"} Share Meeting
      %button{:class => "btn btn-default", :id => "email-meeting"} Email meeting info
      %button{:class => "btn btn-default", :id => "text-meeting"} Text Meeting
    %p#url{:onclick => "selectText(this);"}
      = request.original_url
  #middle-wrapper
    #counter-wrapper
      %span#dollar-sign $
      #flipcountdown
    %button{:class => "btn btn-success hideable", :id => "end-meeting"} End Meeting
    -##catwrap
    -#  #cat
    %p#ended-meeting-message This meeting has ended.
  #participants
    - (@meeting.participant_count-@meeting.checked_out_participant_count).times do
      %span.checked-in.glyphicon.glyphicon-user
    - @meeting.checked_out_participant_count.times do
      %span.checked-out.glyphicon.glyphicon-user
  #checkout
    %button{:class => "btn btn-success hideable hide-on-finish", :id => "checkout-meeting"} Check Out of This Meeting
  #new-meeting-wrapper
    %a{:class => "btn btn-danger show-on-finish",
       :id => "new-meeting",
       :href => root_path,
       :data => { no_turbolink: true }} Start a New Meeting
  #email-modal.modal.fade
    .modal-dialog
      .modal-content
        .modal-header
          %button{:type => "button", :class => "close", :data => {:dismiss => "modal"}}
            %span{:aria => {:hidden => "true"}} &times;
            %span{:class => "sr-only"} Close
          %h4.modal-title Email meeting info
        .modal-body
          %form{:action => "/email", :id => "email-form"}
            %input{:type => "hidden", :name => "id", :value => @meeting.id}
            %input{:type => "hidden", :name => "cost", :value => @meeting.cost, :id => "email-cost"}
            %input{:type => "text", :name => "email", :placeholder => "Email Address"}
            %textarea{:name => "meeting_notes", :placeholder => "Meeting notes"}
            %input{:type => "submit", :value => "Send Email", :class => "btn btn-success"}
        .modal-footer
  #text-modal.modal.fade
    .modal-dialog
      .modal-content
        .modal-header
          %button{:type => "button", :class => "close", :data => {:dismiss => "modal"}}
            %span{:aria => {:hidden => "true"}} &times;
            %span{:class => "sr-only"} Close
          %h4.modal-title Text Meeting
        .modal-body
          %form{:action => "/meetings/#{@meeting.id}/twilio/", :id => "text-form", :method => "post"}
            %input{:type => "text", :name => "phone_number_to_text", :placeholder => "Phone Number To Text"}
            %input{:type => "submit", :value => "Send Text", :class => "btn btn-success"}
        .modal-footer

app/views/welcome/_counter_page.html.haml
#counter-page
  #middle-wrapper
    #counter-wrapper
      %span#dollar-sign $
      #flipcountdown
    %button{:class => "btn btn-danger", :id => "end-meeting"} End Meeting

app/views/welcome/index.html.haml
#welcome-page
  %h1 wasted
  %p#tagline find out how much money you're wasting
  #main-form-wrapper
    %form{:id => "main-form", :class => "pure-form"}
      %input{:type => "text", :name => "num-people", :id => "num-people", :placeholder => "How many people are in the meeting?"}
      %input{:type => "text", :name => "salary", :id => "salary", :value => "90000",
             :data => {:slider => "true",
                       :slider_range => "10000,200000",
                       :slider_step => "5000"}}
      %span.output
        Average Salary: $90,000
      %input{:type => "submit", :value => "Start Meeting", :class => "btn btn-success", :id => "main-form-submit"}
= render "counter_page"